# -*- coding: utf-8 -*-
"""Simulated Employee Performance Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEoGp2F1C9kfkcFLsPzsaWpFONBXa2lx
"""

# ==============================================
# Exploring Simulated Employee Performance Data
# ==============================================

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# For reproducibility
np.random.seed(42)

# -------------------------------
# 1. Generate Synthetic Dataset
# -------------------------------

num_records = 250

employee_ids = np.arange(1, num_records + 1)
years_experience = np.random.randint(1, 21, num_records)      # 1–20 years
training_hours = np.random.randint(10, 201, num_records)      # 10–200 hours

# Performance Score formula
performance_score = (
    50
    + (years_experience * 1.2)
    + (training_hours * 0.1)
    + np.random.normal(0, 5, num_records)
)

# Limit score between 50 and 100
performance_score = np.clip(performance_score, 50, 100)

# Create DataFrame
df = pd.DataFrame({
    "EmployeeID": employee_ids,
    "Years of Experience": years_experience,
    "Training Hours": training_hours,
    "Performance Score": performance_score
})

print("First 5 Records:")
display(df.head())

# ----------------------------------------
# 2. Descriptive Statistical Analysis
# ----------------------------------------

print("\nDescriptive Statistics for Performance Score:\n")

mean_score = df["Performance Score"].mean()
median_score = df["Performance Score"].median()
std_score = df["Performance Score"].std()
min_score = df["Performance Score"].min()
max_score = df["Performance Score"].max()

print(f"Mean: {mean_score:.2f}")
print(f"Median: {median_score:.2f}")
print(f"Standard Deviation: {std_score:.2f}")
print(f"Minimum: {min_score:.2f}")
print(f"Maximum: {max_score:.2f}")

# ----------------------------------------
# 3. Visualizations
# ----------------------------------------

# Histogram
plt.figure(figsize=(8,5))
plt.hist(df["Performance Score"], bins=15)
plt.title("Histogram of Performance Scores")
plt.xlabel("Performance Score")
plt.ylabel("Frequency")
plt.show()

# Scatter Plot
plt.figure(figsize=(8,5))
plt.scatter(df["Years of Experience"], df["Performance Score"])
plt.title("Years of Experience vs Performance Score")
plt.xlabel("Years of Experience")
plt.ylabel("Performance Score")
plt.show()

# ----------------------------------------
# 4. Interpretation
# ----------------------------------------

print("\nAnalysis Summary:")
print("1. The average performance score is relatively high (~70+).")
print("2. Standard deviation indicates moderate variation among employees.")
print("3. Histogram shows most scores fall between 65 and 85.")
print("4. Scatter plot shows a positive relationship between experience and performance.")